### ISSUE TITLE
There's another error in your app.jsx file my friend <3 

### ISSUE THREAD

**Issue by ClexyT** [vaancillo/aprendiendo-react#5]
again :)

**Comment by ClexyT** [comment]
👍

**Comment by ClexyT** [comment]
Para quitar el olor de los dedos después de manipular comida, puedes frotarlos con un algodón mojado en alcohol o agua oxigenada y luego lavarlos con jabón neutro enjuagando muy bien. [También es importante que te hidrates con crema después para que no se te resequen ni sientas acartonadas las manos](https://www.animalgourmet.com/2019/07/22/remedios-quitar-mal-olor-manos/)[1](https://www.animalgourmet.com/2019/07/22/remedios-quitar-mal-olor-manos/).

[Otra opción es poner rodajas de limones en agua hirviendo o algodón humedecido en extracto de vainilla](https://www.cleanipedia.com/ar/limpieza-de-la-cocina/como-sacar-el-olor-a-comida-de-la-casa.html)[2](https://www.cleanipedia.com/ar/limpieza-de-la-cocina/como-sacar-el-olor-a-comida-de-la-casa.html).

Espero que esto te ayude.

**Comment by vaancillo** [comment]
ok 🐱‍👤

**Comment by ClexyT** [comment]
@vaancillo

**Comment by ClexyT** [comment]
im sorry ms jackson

**Comment by vaancillo** [comment]
oooh i'm for real

**Comment by ClexyT** [comment]
never meant to make your daughter cry :C

**Comment by vaancillo** [comment]
I apologize a trillion times
My baby's drama mama, don't like me
